// Code generated by MockGen. DO NOT EDIT.
// Source: seat_repo.go

// Package seatrepo is a generated GoMock package.
package seatrepo

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	seat "github.com/codepnw/stdlib-ticket-system/internal/features/seat"
	gomock "github.com/golang/mock/gomock"
)

// MockSeatRepository is a mock of SeatRepository interface.
type MockSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatRepositoryMockRecorder
}

// MockSeatRepositoryMockRecorder is the mock recorder for MockSeatRepository.
type MockSeatRepositoryMockRecorder struct {
	mock *MockSeatRepository
}

// NewMockSeatRepository creates a new mock instance.
func NewMockSeatRepository(ctrl *gomock.Controller) *MockSeatRepository {
	mock := &MockSeatRepository{ctrl: ctrl}
	mock.recorder = &MockSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatRepository) EXPECT() *MockSeatRepositoryMockRecorder {
	return m.recorder
}

// CreateSeatBatchTx mocks base method.
func (m *MockSeatRepository) CreateSeatBatchTx(ctx context.Context, tx *sql.Tx, seats []seat.Seat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeatBatchTx", ctx, tx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeatBatchTx indicates an expected call of CreateSeatBatchTx.
func (mr *MockSeatRepositoryMockRecorder) CreateSeatBatchTx(ctx, tx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeatBatchTx", reflect.TypeOf((*MockSeatRepository)(nil).CreateSeatBatchTx), ctx, tx, seats)
}

// GetSeatsByEventID mocks base method.
func (m *MockSeatRepository) GetSeatsByEventID(ctx context.Context, eventID int64) ([]seat.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatsByEventID", ctx, eventID)
	ret0, _ := ret[0].([]seat.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatsByEventID indicates an expected call of GetSeatsByEventID.
func (mr *MockSeatRepositoryMockRecorder) GetSeatsByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatsByEventID", reflect.TypeOf((*MockSeatRepository)(nil).GetSeatsByEventID), ctx, eventID)
}

// GetSeatsForUpdateTx mocks base method.
func (m *MockSeatRepository) GetSeatsForUpdateTx(ctx context.Context, tx *sql.Tx, seatIDs []int64) ([]seat.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatsForUpdateTx", ctx, tx, seatIDs)
	ret0, _ := ret[0].([]seat.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatsForUpdateTx indicates an expected call of GetSeatsForUpdateTx.
func (mr *MockSeatRepositoryMockRecorder) GetSeatsForUpdateTx(ctx, tx, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatsForUpdateTx", reflect.TypeOf((*MockSeatRepository)(nil).GetSeatsForUpdateTx), ctx, tx, seatIDs)
}

// UpdateSeatsStatusTx mocks base method.
func (m *MockSeatRepository) UpdateSeatsStatusTx(ctx context.Context, tx *sql.Tx, seatIDs []int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeatsStatusTx", ctx, tx, seatIDs, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeatsStatusTx indicates an expected call of UpdateSeatsStatusTx.
func (mr *MockSeatRepositoryMockRecorder) UpdateSeatsStatusTx(ctx, tx, seatIDs, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeatsStatusTx", reflect.TypeOf((*MockSeatRepository)(nil).UpdateSeatsStatusTx), ctx, tx, seatIDs, status)
}
