// Code generated by MockGen. DO NOT EDIT.
// Source: booking_repo.go

// Package bookingrepo is a generated GoMock package.
package bookingrepo

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	booking "github.com/codepnw/stdlib-ticket-system/internal/features/booking"
	gomock "github.com/golang/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CreateBookingItemsTx mocks base method.
func (m *MockBookingRepository) CreateBookingItemsTx(ctx context.Context, tx *sql.Tx, bookingID string, seatIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookingItemsTx", ctx, tx, bookingID, seatIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBookingItemsTx indicates an expected call of CreateBookingItemsTx.
func (mr *MockBookingRepositoryMockRecorder) CreateBookingItemsTx(ctx, tx, bookingID, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookingItemsTx", reflect.TypeOf((*MockBookingRepository)(nil).CreateBookingItemsTx), ctx, tx, bookingID, seatIDs)
}

// CreateBookingTx mocks base method.
func (m *MockBookingRepository) CreateBookingTx(ctx context.Context, tx *sql.Tx, input booking.Booking) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookingTx", ctx, tx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookingTx indicates an expected call of CreateBookingTx.
func (mr *MockBookingRepositoryMockRecorder) CreateBookingTx(ctx, tx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookingTx", reflect.TypeOf((*MockBookingRepository)(nil).CreateBookingTx), ctx, tx, input)
}
